name: app
description: "Ung dung truy xuat nguon goc nong san tich hop blockchain."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.4.3+1
  mobile_scanner: ^5.1.1
  image_picker: ^1.1.2
  timeline_tile: ^2.0.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  share_plus: ^10.0.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
